name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    # On Windows, install MSYS2 + mingw gcc so `gcc` is available
    - name: Setup MSYS2 (Windows)
      if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2 # v3 has a bug with pathing, v2 is recommended
      with:
        update: true
        install: >
          mingw-w64-x86_64-gcc

    - name: Compile tests
      shell: msys2 {0} # Use msys2 shell on Windows for consistency
      run: |
        if [ "$RUNNER_OS" = "Windows" ]; then
          # MSYS2 puts mingw64 gcc on PATH in GitHub runners after setup
          gcc -o tests/test_runner.exe tests/test_runner.c -I. -std=c99 -Wall -Wextra -pedantic -mconsole
        else
          gcc -o tests/test_runner tests/test_runner.c -I. -std=c99 -Wall -Wextra -pedantic
        fi

    - name: Run tests
      shell: msys2 {0}
      run: |
        if [ "$RUNNER_OS" = "Windows" ]; then
          ./tests/test_runner.exe
        else
          ./tests/test_runner
        fi
